services:
  backend:
    build:
      context: ./docker-compose/php-fpm
      dockerfile: Dockerfile
      args:
        user: enrico
        uid: 1000
        basepath: ${BASE_PATH}
    image: unicontr
    container_name: unicontr-backend
    working_dir: ${BASE_PATH}
    volumes:
      - ../unicontract-backend:${BASE_PATH}
    networks:
      - app-network
    depends_on:
      - db

  db:
    image: mariadb:10.11
    container_name: unicontr-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: unicontr
      MYSQL_ROOT_PASSWORD: rootsecret
      MYSQL_USER: unicontr
      MYSQL_PASSWORD: secret
    volumes:
      - ./docker-compose/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - app-network

  idp:
    build:
      context: ../unicontract-mock-idp
      dockerfile: ../unicontract-docker/docker-compose/mock-idp/Dockerfile
    container_name: unicontr-idp
    ports:
      - "7000:7000"
    volumes:
      - ../unicontract-mock-idp/start.js:/usr/src/app/start.js
    command: bash -c "node start.js"

  # Comment this out to use Caddy instead of Nginx for out of the box HTTPS support
  nginx:
    build:
      context: ../unicontract-frontend
      dockerfile: ../unicontract-docker/docker-compose/nginx/Dockerfile
    container_name: unicontr-nginx
    tty: true
    restart: unless-stopped

    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../unicontract-backend:${BASE_PATH}
      - ./docker-compose/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network

  # Comment this out to use Nginx instead of Caddy
  # caddy:
  #   build:
  #     context: ../unicontract-frontend
  #     dockerfile: ../unicontract-docker/docker-compose/caddy/Dockerfile
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #     - "443:443/udp"
  #   volumes:
  #     - ../unicontract-backend:${BASE_PATH}
  #     - ./docker-compose/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
  #     - caddy_data:/data
  #     - caddy_config:/config
  #   depends_on:
  #     - backend
  #   networks:
  #     - app-network
  #   restart: unless-stopped

volumes:
  caddy_data:
  caddy_config:

networks:
  app-network:
    driver: bridge
